Fixed NoSuchMethodError on all devices prior to JellyBean (SDK 16)
In LegacyDialog the call to setBackground() caused a NoSuchMethodError since prior to JellyBean this method was names setBackgroundDrawable().